service: users-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}

resources: ${file(resources/resources.yml)}

functions: ${file(functions.yml)}

custom:
  serverless-offline:
    httpPort: 4321
