GenericUserPool:
  Type: 'AWS::Cognito::UserPool'
  Properties:
    UserPoolName: memestock-generic-user
    MfaConfiguration: OFF
    # AccountRecoverySetting:
    #   - email
    AliasAttributes:
      - email
      - preferred_username
    # UsernameAttributes:
    #   - email
    #   - 'userId'
    #   - 'username'
    Schema:
      - Name: email
        Required: true
        Mutable: true
      - Name: 'userId'
        Mutable: false
        AttributeDataType: String
    Policies:
      PasswordPolicy:
        MinimumLength: 6
        RequireLowercase: False
        RequireNumbers: True
        RequireSymbols: False
        RequireUppercase: True
