service: users-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-cloudside-plugin

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
  environment:
    USERS_TABLE_NAME: !Ref UsersTable
    COMPANY_SERVICE_URL: 'https://a8sxo3zyr8.execute-api.us-east-1.amazonaws.com/dev'
    COGNITO_GENERIC_USER_POOL_ID: !Ref GenericUserPool
    COGNITO_GENERIC_USER_CLIENT_ID: !Ref GenericUserClient

resources: ${file(resources/resources.yml)}

functions: ${file(functions.yml)}

custom:
  serverless-offline:
    httpPort: 4321
