CompaniesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: CompaniesTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: documentType
        AttributeType: S
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: documentType
        KeySchema:
          - AttributeName: documentType
            KeyType: HASH
        Projection:
          ProjectionType: ALL
