CompaniesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: CompaniesTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
