service: order-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-cloudside-plugin

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/OrdersTableIAM.yml):OrdersTableIAM}
  environment:
    ORDERS_TABLE_NAME: !Ref OrdersTable
    GSI_STATUS_AND_CREATED: 'statusAndCreated'

resources: ${file(resources/resources.yml)}

functions: ${file(functions.yml)}

custom:
  serverless-offline:
    httpPort: 4321
