service: order-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-cloudside-plugin

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/OrdersTableIAM.yml):OrdersTableIAM}
  environment:
    ORDERS_TABLE_NAME: !Ref OrdersTable
    USER_SERVICE_URL: 'https://741a1l025i.execute-api.us-east-1.amazonaws.com/dev'
    TRANSACTION_SERVICE_URL: 'https://727yqlfk78.execute-api.us-east-1.amazonaws.com/dev'
    GSI_STATUS_AND_CREATED: 'statusAndCreated'
    GSI_USER_ID_AND_CREATED: 'userIdAndCreated'

resources: ${file(resources/resources.yml)}

functions: ${file(functions.yml)}

custom:
  serverless-offline:
    httpPort: 4321
