service: ai-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-cloudside-plugin

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/AiProfilesTableIAM.yml):AiProfilesTableIAM}
    - ${file(iam/AiActionsTableIAM.yml):AiActionsTableIAM}
  environment:
    AI_PROFILES_TABLE_NAME: !Ref AiProfilesTable
    AI_ACTIONS_TABLE_NAME: !Ref AiActionsTable
    GSI_STATUS_AND_CREATED: 'statusAndCreated'
    USER_SERVICE_URL: 'https://omijfe4bic.execute-api.us-east-1.amazonaws.com/dev'

resources: ${file(resources/resources.yml)}

functions: ${file(functions.yml)}

custom:
  serverless-offline:
    httpPort: 4321
