OrdersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: OrdersTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: created
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: statusAndCreated
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: created
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: userIdAndCreated
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: created
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
